version: '3.8'

# version: '3.3'

x-logging: &default-logging
  options:
    max-size: "10M"
    max-file: "10" 
  driver: json-file


services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      - mongodb
    command: uvicorn main:app --host 0.0.0.0 --port 8010 --reload
    environment:
      - MONGO_URL=mongodb://mongodb:27018/
    volumes:
      - ./backend/app:/app 
  
  mongodb:
    hostname : mongodb
    image: "mongo:latest"
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db
    # networks:
      # - civil_air
    logging: *default-logging
    command: mongod --port 27018
  
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  mongodb_data:


# networks:
#   civil_air:
#     external: true